### ISSUE TITLE
wanna use your config

### ISSUE THREAD

**Issue by abdoulayegk** [Gako358/Dotfiles#2]
Hey I really love your work. This config looks amazing I wanna use it but it's failing are you going to make an installation script for this?

**Comment by Gako358** [comment]
Are you then talking about the images?
then: [https://github.com/Gako358/Dotfiles/tree/2b654c3c87864710774cdd64ee1dd26ebdc325e4/.archive](url)

and copy the bspwm, sxhkd and polybar folders into your .config folder and of course install them. Then  You will get the same setup as on the pictures.

If anything else, please just leave more comments, glad you like it.
